credentials:
  usernames:
    lpanigrahi:
      email: lpanigrahi@judge.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Lalatendu Panigrahi
      password: abc # Will be hashed automatically
    judge:
      email: aimlsolutions@judge.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Judge India Pvt Ltd.
      password: judge123 # Will be hashed automatically
    Guest:
      email: aimlsolutions@judge.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Guest User Login!
      password: judge123 # Will be hashed automatically
    Landmark:
      email: aimlsolutions@judge.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Landmark User Login!
      password: india123 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - lpanigrahi@judge.com